### ISSUE TITLE
Historical College Basketball Rankings?

### ISSUE THREAD

**Issue by aqsmith08** [jeffself/collegebasketballrankings#1]
Hi Jeff,

Thanks for creating and running your College Basketball Rankings. It looks like it updates daily. Do you retain the historical records so that folks can see how those rankings changed over time (e.g., daily or weekly)? If so, I'd love to get access to that data especially for the 2017-2018 and 2018-2019 seasons.

Best,
Aaron

**Comment by jeffself** [comment]
My rankings are updated weekly since the website I use for scores gets updated weekly. I tried using the NCAA’s site but it seemed like the data wasn’t always accurate. 

Currently, my rankings are hosted on GitHub. I have rankings going back to 2007.

In order to see how my rankings change, you would have to look at my rankings on github and look at the history of changes to the file.

**Comment by aqsmith08** [comment]
Got it. I've never done it before but there's likely a way I can pull that. Thanks, appreciate your response. I'll poke around from here. Closing.
